### ISSUE TITLE
Multiple currencies in multiple items

### ISSUE THREAD

**Issue by cavalle** [invopop/gobl#187]
At the moment, GOBL allows to specify the currency at item level, if the currency is different than the invoice's one. However, at the time of calculating totals, different lines with different currencies are summed together as if they had the same currency.

We need to review this behaviour as probably the exchange rates information (if present) should be used to calculate totals in the invoice's currency properly (or a validation error be returned if the exchange rates required to calculate the totals are missing)

**Comment by samlown** [comment]
This one is solved now 👍
