### ISSUE TITLE
Calculate() panics when using addons on invoices with no lines

### ISSUE THREAD

**Issue by tomasguinzburg** [invopop/gobl#424]
Hey! We are entertaining the use of addons on our side to catch early validation errors, and we spotted a change in behaviour in the `(bill.Invoice) Calculate()` method when using them.

Granted, an invoice with no items is not a valid invoice, but this is spotted in validation with a graceful error, as opposed to the panic we are getting now during calculation. Preventing this panic leads to cleaner code in library users, as they can avoid manually validating for empty invoices.

It can be reproduced by adding the following test in [saft scenario_test](https://github.com/invopop/gobl/blob/1a3f64f7f5cfbe874becb2a3eeb8f6b5cb7b2d7c/addons/pt/saft/scenarios_test.go), but it happens with any addon that defines scenarios and there's probably better spots for it.

```go
func invoiceNoItems() *bill.Invoice {
	return &bill.Invoice{
		Regime: tax.WithRegime("PT"),
		Supplier: &org.Party{
			TaxID: &tax.Identity{
				Code:    "123456789",
				Country: "PT",
			},
			Name: "Test Supplier",
		},
		Customer: &org.Party{
			Name: "Test Customer",
		},
		Code:      "INV/1",
		Currency:  "EUR",
		IssueDate: cal.MakeDate(2023, 1, 1),
	}
}

func TestInvoiceNoItems(t *testing.T) {
	inv := invoiceNoItems()
	err := inv.Calculate()
	assert.NoError(t, err)
	// Passes
}

func TestInvoiceNoItemsAddon(t *testing.T) {
	inv := invoiceNoItems()
	inv.Addons = tax.WithAddons(saft.V1)
	err := inv.Calculate()
	// Panics here 
	// on https://github.com/invopop/gobl/blob/5c886d5d2e70fc5899b205774dc19e5912bd7c43/bill/invoice_scenarios.go:22
	t.Fail()
}
```

This patch to invoice_scenarios.go:22 should fix it:
```go
if inv.Totals != nil && inv.Totals.Taxes != nil {
	for _, cat := range inv.Totals.Taxes.Categories {
		for _, rate := range cat.Rates {
			exts = append(exts, rate.Ext)
		}
	}
}
```

I understand an invoice with no items is not a common use case and in fact does not pass validations, but I don't think this panic is desirable. We can open a PR for these, please let me know your thoughts.

Thanks!

**Comment by samlown** [comment]
Thanks @tomasguinzburg! So this sounds like a bug whereby the lack of lines is not taken into account. We're actually planning to make lines optional if either `charges` or `discounts` are present, so we do indeed need to fix this. We'll have a look 👍
